### ISSUE TITLE
Error: Perfect separation detected, results not available

### ISSUE THREAD

**Issue by wiekern** [benmiroglio/pymatch#29]
Hi,
I met an error described in the title when invoking `fit_scores()`. My data structrue is below
![image](https://user-images.githubusercontent.com/3865455/68478831-2673d580-0231-11ea-9949-b530cfd18a5d.png)

and I draw samples 2000 for test, 20000 for control for fitting the matcher, but I have no clue why this error occurs (I have looked into the source code). In addition, I ran the example code for loan.csv successfully, so I wonder if the fields of the data should not be string, rather integer? In fact, the data structure of loan example contains string as well see below
![image](https://user-images.githubusercontent.com/3865455/68479036-a732d180-0231-11ea-91c6-1c57ecf228c9.png)

Hope anyone can help, thanks!

**Comment by mark-mediware** [comment]
@wiekern Not sure if it helps you, but I had similar errors and was pretty stuck. After some basic data analysis, I realized I had a few input variables with very limited distribution across groups (ex. Binary age bin with 10,000 rows = 0, and 5 rows = 1). After removing these variables/features, I had no errors.

Again, not sure if that's applicable to you, but was my (embarrassing ) issue.

**Comment by wiekern** [comment]
Thanks for your answer! 
The distribution might not be the problem, that was my view. I am wondering if the regression model supports input with string like in my case column of "text". I am think of I must be convert text into a numeric value or word embeddings (vector).

**Comment by umangdadhaniya** [comment]
model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = train_data).fit()
Traceback (most recent call last):

  File "<ipython-input-507-01d3a972ebbd>", line 1, in <module>
    model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = train_data).fit()

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 1963, in fit
    bnryfit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 227, in fit
    mlefit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\model.py", line 519, in fit
    xopt, retvals, optim_settings = optimizer._fit(f, score, start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 215, in _fit
    xopt, retvals = func(objective, gradient, start_params, fargs, kwargs,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 327, in _fit_newton
    callback(newparams)

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 211, in _check_perfect_pred
    raise PerfectSeparationError(msg)

PerfectSeparationError: Perfect separation detected, results not available


model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = train_data).fit()
Traceback (most recent call last):

  File "<ipython-input-508-01d3a972ebbd>", line 1, in <module>
    model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = train_data).fit()

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 1963, in fit
    bnryfit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 227, in fit
    mlefit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\model.py", line 519, in fit
    xopt, retvals, optim_settings = optimizer._fit(f, score, start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 215, in _fit
    xopt, retvals = func(objective, gradient, start_params, fargs, kwargs,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 327, in _fit_newton
    callback(newparams)

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 211, in _check_perfect_pred
    raise PerfectSeparationError(msg)

PerfectSeparationError: Perfect separation detected, results not available
